version: "3"
services:
    price-calculator-local:
        image: postgres
        restart: always
        container_name: aton-user-management-local
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "user-manager"
            POSTGRES_PASSWORD: "123456"
        ports:
            - 15432:5432
